name: Docker Image CI with Tag

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - Dockerfile
      - requirements.txt
      - setup.py
    tags:
      - '*'
  
jobs:
  push_to_registry:
    name: Push tagged docker image to GitHub Container Registry
    runs-on: gallis-gh-runner
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.title=${GITHUB_REPOSITORY#*/}
            org.opencontainers.image.description=Sentinel MCP Server
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.created={{date 'yyyy-MM-ddTHH:mm:ssZ'}}
            org.opencontainers.image.revision=${{ github.sha }}
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max